spring:
  application:
    name: edacyEvent
  datasource:
    url: jdbc:mysql://localhost:3304/edacyEventDb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    ROOT: info
    # debug level for all use defined code logs
  edacy.edacyEvent: info
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000  # 1 hour in milliseconds
    refresh-expiration-time: 3600000
